#!/bin/sh

# remove workspace files older than 24 days
find /srv/buildd/workspace -mindepth 1 -maxdepth 1 -type d -mtime +24 -exec rm -rf -- '{}' \;

# clean up any debs that haven't been used in a month
find /var/cache/pbuilder/aptcache/ -atime +30 -exec rm -f -- '{}' \;
