#!/bin/bash

checks_and_defaults() {
  if [ -r /etc/jenkins/debian_glue ] ; then
    . /etc/jenkins/debian_glue
  fi

  if [ -z "${OUTGOING_DIR:-}" ] ; then
    OUTGOING_DIR='/srv/buildd/outgoing'
  fi

  if [ -z "${LOG_DIR:-}" ] ; then
    LOG_DIR='/srv/buildd/logs'
  fi
}

process_uploads() {
  cd $OUTGOING_DIR

  count=`ls -1 *.changes 2>/dev/null | wc -l`
  if [ $count == 0 ]
  then
    return 0
  fi

  for changesfile in *.changes
  do
    dput tanglu-ftpmaster $changesfile
    rc=$?
    if [[ $rc != 0 ]] ; then
      mv "$changesfile" "$changesfile.upload-failed"
    fi
  done

  cd /tmp
}

delete_cruft() {
  [ "$(ls -A $OUTGOING_DIR)" ] && find $OUTGOING_DIR -mtime +4 -exec rm {} \;
}

exec >> "${LOG_DIR}/uploader.log" 2>&1

checks_and_defaults
process_uploads
delete_cruft
