#!/bin/bash

set -e

install_packages() {
    apt-get -y "${APTGETOPT[@]}" install "$@"
}

install_packages lintian

echo "+++ lintian output +++"

HOME=/tmp/lintian_home su -mc "cd /tmp && lintian -I --show-overrides /tmp/buildd/*.changes; :" - buildd

echo "+++ end of lintian output +++"
