#!/bin/bash

set -e

install_packages() {
    apt-get -y "${APTGETOPT[@]}" install "$@"
}

install_packages lintian

echo "+++ lintian output +++"

su -c "lintian -I --show-overrides /tmp/buildd/*.changes; :" - buildd

echo "+++ end of lintian output +++"
