#!/bin/bash

set -e

install_packages() {
    apt-get -y "${APTGETOPT[@]}" install "$@"
}

install_packages lintian

echo "+++ lintian output +++"

lintian -IE --show-overrides /tmp/buildd/*.changes

echo "+++ end of lintian output +++"
